services:
  - type: web
    name: vigiscan
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: VIGISCAN_MAIL_USER
        sync: false
      - key: VIGISCAN_MAIL_PASS
        sync: false
    disk:
      name: vigiscan-data
      mountPath: /data
      sizeGB: 1
